### ISSUE TITLE
Lost Media Queries

### ISSUE THREAD

**Issue by gruzzilkin** [lexich/gulp-webpcss#2]
Hi! I found another one bug:

**before**:

``` css
@media only screen and (-webkit-min-device-pixel-ratio:1.5),only screen and (min-resolution:2dppx) {
    .select2-container .select2-choice .select2-arrow b,.select2-container .select2-choice abbr,.select2-search input,.select2-search-choice-close {
        background-image: url(../i/plugins/select2/select2x2.png);
    }
}
```

**after**:

``` css
.webp .select2-container .select2-choice .select2-arrow b,.webp .select2-container .select2-choice abbr,.webp .select2-search input,.webp .select2-search-choice-close {
    background-image: url(../i/plugins/select2/select2x2.webp)
}
```
